sudo: false
language: node_js
node_js:
  - '10'

os:
  - osx
  - linux
  - windows

script:
  - npm install
  - npm rebuild
  - npm run build
  - npm run dist

deploy:
  provider: script
  script: npm run dist
  on:
    all_branches: true
  skip_cleanup: true
  file_glob: true
